### ISSUE TITLE
Importing existing ARB files

### ISSUE THREAD

**Issue by DFelten** [Arbify/Arbify#14]
Arbify looks great, thanks! 

One thing I'm missing is the possibility to import existing arb . I only found the option to export them. 

This would be a great addition!

**Comment by Albert221** [comment]
I had this feature in my mind. Will do at some point!

**Comment by Albert221** [comment]
Work has started on [the aw-import branch](https://github.com/Arbify/Arbify/tree/aw-import).

**Comment by Albert221** [comment]
I hope you'll like the initial support for importing! :)

https://twitter.com/albert_wolszon/status/1267063599475941377

**Comment by DFelten** [comment]
The import works great, thanks!
