### ISSUE TITLE
arbify

### ISSUE THREAD

**Issue by amit-uipep** [Arbify/Arbify#60]
docker-compose run --rm arbify docker/arbify/upgrade.sh
Creating arbify_arbify_run ... done
/usr/bin/env: 'bash\r': No such file or directory

**Comment by amit-uipep** [comment]
getting bad state upgrade and run this command also 
docker-compose run --rm arbify docker/arbify/upgrade.sh

**Comment by Albert221** [comment]
Please, refer to this answer on StackOverflow: https://stackoverflow.com/a/29045187/3158312

**Comment by Nikzed** [comment]
It's the problem with CRLF formatting. I use Android Studio so I just simply open Arbify projects, press root folder File -> File Properties -> Line separator -> change it to CF
![image](https://github.com/Arbify/Arbify/assets/38156331/f2040d27-e23a-45d0-8b63-552b5e94031b)
