### ISSUE TITLE
TIP: External database

### ISSUE THREAD

**Issue by henry2man** [Arbify/Arbify#66]
Given the fact that this project is abandoned I want to share here **how to use Arbify with an external database** (I think an issue will be the best way to give it visibility) 

Steps:

1. Create external database & user
2. Ensure that your host machine can connect to the database (you can simply execute `telnet <dbhost> <dbport>`)
3. Modify your docker-compose.yaml to include additional parameters in the arbify definition (please ensure that your .env file contains a whole-valid external database configuration):

```
         working_dir: /var/www
         environment:
+            DB_CONNECTION: ${DB_CONNECTION}
+            DB_HOST: ${DB_HOST}
+            DB_PORT: ${DB_PORT}
+            DB_DATABASE: ${DB_DATABASE}
             DB_USER: ${DB_USERNAME}
             DB_PASSWORD: ${DB_PASSWORD}
```

4. Delete from docker-compose.yaml the mariadb container
5. **Modify the upgrade.sh script to allow external connections** (notice that you'll need to add `-h ${DB_HOST}` in order to connect to the remote database)

```
--- a/docker/arbify/upgrade.sh
+++ b/docker/arbify/upgrade.sh
@@ -12,7 +12,7 @@ fi
 # Wait until db is operational
 echo "2/5   Running migrations on database..."
 counter=1
-while ! mysql -h db -u "${DB_USER}" --password="${DB_PASSWORD}" -e "SHOW DATABASES;" > /dev/null 2>&1; do
+while ! mysql -h "${DB_HOST}" -u "${DB_USER}" --password="${DB_PASSWORD}" -e "SHOW DATABASES;" > /dev/null 2>&1; do
     sleep 1
     counter=`expr ${counter} + 1`
     if [[ ${counter} -gt 10 ]]; then
```

6. With this changes in place, you can simply follow installation instructions and you'll have a working installation on your server. 

PS: For posterity, I also want to comment that I was able to run all of this on a simple Raspberry Pi 4

**Comment by henry2man** [comment]
👀  @huang12zheng You'll probably be interested on this 👍

**Comment by huang12zheng** [comment]
thanks, but I've given up last mouth.

The answer may not be right,
In my opinion, the docker volumn should be able to save database data
