### ISSUE TITLE
Error for `docker-compose up`

### ISSUE THREAD

**Issue by Gorniv** [Arbify/Arbify#7]
Warning: require(/var/www/public/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/public/index.php on line 24

Fatal error: require(): Failed opening required '/var/www/public/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/public/index.php on line 24

**Comment by Albert221** [comment]
Hi! Thanks for trying out Arbify!

After running `docker-compose up` you need to run few build commands on the first run to build the project. It's all ready for copy & paste in [README Installation section here](https://github.com/Arbify/Arbify#installation).

I know it's not ideal, Docker setup will be improved at some point, but for now it's just running few more easily copy-and-pasted commands :)

Please respond if this works for you!

**Comment by Gorniv** [comment]
Hi. so many steps, i think that that i need only `docker-compose up -d` :D
now:
GET http://localhost:8000/js/app.js net::ERR_ABORTED 404 (Not Found)
GET http://localhost:8000/css/app.css net::ERR_ABORTED 404 (Not Found)

**Comment by Albert221** [comment]
I think that you did not run `npm run prod` in the arbify container. The very last command

**Comment by Gorniv** [comment]
Gorniv:Arbify gorniv$ docker-compose run --rm arbify php artisan db:seed
Seeding: LanguageSeeder

   Illuminate\Database\QueryException 

  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'en' for key 'languages_code_unique' (SQL: insert into `languages` (`code`, `flag`, `name`, `plural_forms`) values (en, united-kingdom, English, 34), (pl, poland, Polish, 26), (es, spain, Spanish, 34))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
    667|         // If an exception occurs when attempting to run a query, we'll format the error
    668|         // message to include the bindings with SQL, which will make this exception a
    669|         // lot more helpful to the developer instead of just the database's errors.
    670|         catch (Exception $e) {
  > 671|             throw new QueryException(
    672|                 $query, $this->prepareBindings($bindings), $e
    673|             );
    674|         }
    675| 

      +9 vendor frames 
  10  database/seeds/LanguageSeeder.php:41
      Illuminate\Database\Query\Builder::insert()

      +8 vendor frames 
  19  database/seeds/DatabaseSeeder.php:9
      Illuminate\Database\Seeder::call("LanguageSeeder")

**Comment by Gorniv** [comment]
fixed with retry commands
